// Generates the blue-noise dither texture (D7) with Ulichney's void-and-cluster
// method and writes it as a TS module, so the renderer can build the texture
// synchronously (also inside a worker). Deterministic for a given seed.
//
//   node scripts/generate-blue-noise.ts
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SIZE = 64;
const SIGMA = 1.5;
const SEED = 0x9e3779b9;
const INITIAL_DENSITY = 0.1;
const OUT = fileURLToPath(new URL('../src/engine/blue-noise.generated.ts', import.meta.url));

function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Void-and-cluster ranks: a permutation of 0..size²-1, row-major. */
function voidAndCluster(size: number, sigma: number, seed: number): Uint16Array {
  const n = size * size;
  // Toroidal Gaussian kernel, indexed by wrapped offset (dy * size + dx).
  const kernel = new Float64Array(n);
  for (let dy = 0; dy < size; dy++) {
    for (let dx = 0; dx < size; dx++) {
      const x = Math.min(dx, size - dx);
      const y = Math.min(dy, size - dy);
      kernel[dy * size + dx] = Math.exp(-(x * x + y * y) / (2 * sigma * sigma));
    }
  }

  // energy[p] = Σ over ones q of kernel(p - q); updated incrementally per flip.
  function flip(pattern: Uint8Array, energy: Float64Array, p: number, value: 0 | 1) {
    pattern[p] = value;
    const sign = value ? 1 : -1;
    const px = p % size;
    const py = (p - px) / size;
    for (let y = 0; y < size; y++) {
      const ky = ((y - py + size) % size) * size;
      const row = y * size;
      for (let x = 0; x < size; x++) energy[row + x] += sign * kernel[ky + ((x - px + size) % size)];
    }
  }
  // Tightest cluster = the one with the highest energy; largest void = the
  // zero with the lowest. Ties go to the lowest index (deterministic).
  function tightestCluster(pattern: Uint8Array, energy: Float64Array) {
    let best = -1;
    for (let i = 0; i < n; i++) if (pattern[i] && (best < 0 || energy[i] > energy[best])) best = i;
    return best;
  }
  function largestVoid(pattern: Uint8Array, energy: Float64Array) {
    let best = -1;
    for (let i = 0; i < n; i++) if (!pattern[i] && (best < 0 || energy[i] < energy[best])) best = i;
    return best;
  }

  // Initial binary pattern: random points, then relaxed until the tightest
  // cluster and the largest void coincide.
  const random = mulberry32(seed);
  const initial = new Uint8Array(n);
  const energy0 = new Float64Array(n);
  const ones = Math.round(n * INITIAL_DENSITY);
  for (let placed = 0; placed < ones;) {
    const p = Math.floor(random() * n);
    if (!initial[p]) {
      flip(initial, energy0, p, 1);
      placed++;
    }
  }
  for (;;) {
    const cluster = tightestCluster(initial, energy0);
    flip(initial, energy0, cluster, 0);
    const hole = largestVoid(initial, energy0);
    if (hole === cluster) {
      flip(initial, energy0, cluster, 1);
      break;
    }
    flip(initial, energy0, hole, 1);
  }

  const ranks = new Uint16Array(n);
  // Phase 1: remove clusters from the initial pattern, ranks ones-1 .. 0.
  {
    const pattern = initial.slice();
    const energy = energy0.slice();
    for (let rank = ones - 1; rank >= 0; rank--) {
      const p = tightestCluster(pattern, energy);
      flip(pattern, energy, p, 0);
      ranks[p] = rank;
    }
  }
  // Phases 2 and 3: fill the largest voids, ranks ones .. n-1. With a linear
  // filter, the densest cluster of zeros is exactly the ones' largest void, so
  // Ulichney's phase 3 reduces to continuing phase 2.
  {
    const pattern = initial.slice();
    const energy = energy0.slice();
    for (let rank = ones; rank < n; rank++) {
      const p = largestVoid(pattern, energy);
      flip(pattern, energy, p, 1);
      ranks[p] = rank;
    }
  }
  return ranks;
}

function toBase64(ranks: Uint16Array): string {
  const bytes = new Uint8Array(ranks.length * 2);
  ranks.forEach((r, i) => {
    bytes[2 * i] = r & 0xff;
    bytes[2 * i + 1] = r >> 8;
  });
  return Buffer.from(bytes).toString('base64');
}

const t0 = performance.now();
const ranks = voidAndCluster(SIZE, SIGMA, SEED);
const lines = toBase64(ranks).match(/.{1,100}/g) ?? [];
const source = `// Generated by scripts/generate-blue-noise.ts — do not edit.
// Void-and-cluster blue noise, ${SIZE}×${SIZE}, sigma ${SIGMA}, seed 0x${SEED.toString(16)}.

export const BLUE_NOISE_SIZE = ${SIZE};

/** Ranks 0..${SIZE * SIZE - 1} (a permutation), row-major, uint16 little-endian, base64. */
export const BLUE_NOISE_RANKS_BASE64 = [
${lines.map((l) => `  '${l}',`).join('\n')}
].join('');
`;
writeFileSync(OUT, source);
console.log(`wrote ${OUT} (${SIZE}×${SIZE}) in ${(performance.now() - t0).toFixed(0)} ms`);
